#!/bin/bash
# create variables
nums=$(echo {0..9})
states=('Texas' 'Ohio' 'NewYork' 'California' 'Hawaii')
ls_out=$(ls)

#create loop for Hawaii
for state in ${states[@]};
do
  if [ $state == ('Hawaii') ]
then
	echo "Hawaii is the best"
else
	echo "Im not dound of Hawaii"
  fi 
done
